# Config
# ========================================================================================

url:                   https://mickey-on-wheels.github.io
baseurl:               ''
lang:                  en

title:                 Mickey on Wheels
description:           >
  Smiles per Gallon.
tagline:               >
  Smiles per Gallon.
keywords:              [Motorsport, Autonomous Driving, Vehicles]

logo:                  /assets/icons/50_jahre_bmw_m.png

author:
  name:                Seokjun Lee
  email:               mickey2953@naver.com

copyright:             Copyright 2026 Seokjun Lee. All rights reserved.

permalink:             pretty
paginate:              10
paginate_path:         /page-:num/


# Hydejack
# ========================================================================================

remote_theme:          hydecorp/hydejack@v9.2.1

accent_image:          /assets/img/cover_img.jpg
accent_color:          '#16588E'

google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

menu:
  - title:             Autonomous Driving
    url:               /category/autonomous-driving/
  - title:             "&nbsp;&nbsp;Tech Trends"
    url:               /tag/tech-trends/
  - title:             "&nbsp;&nbsp;Paper Review"
    url:               /tag/paper-review/
  - title:             Motorsport
    url:               /category/motorsport/
  - title:             Mickey's Car Life
    url:               /category/mickeys-car-life/
  - title:             Hyde
    url:               /tag/hyde/
  - title:             Hydejack
    url:               /tag/hydejack/
  - title:             About
    url:               /about/
  - title:             Documentation
    url:               /docs/

hydejack:
  post_addons:         [about, related]
  project_addons:      [about, other]
  no_google_fonts:     false
  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     false
  no_structured_data:  false
  no_theme_color:      false
  use_lsi:             false
  cookies_banner:      false


# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /category/:name/
    output:            true

  featured_tags:
    permalink:         /tag/:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true


# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
include:
  - LICENSE.md


# Plugins and Plugin Configuration
# ========================================================================================

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed
